#!/usr/bin/env python3
"""Summarize the structured ACC Q/TD diagnostics emitted during training."""

import argparse
import json
from collections import defaultdict
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--method", default="acc")
    return parser.parse_args()


def maximum(rows, key):
    return max(float(row[key]) for row in rows)


def main():
    args = parse_args()
    model_dir = args.run_dir / args.method / "models"
    metric_files = sorted(model_dir.glob("*_metrics.jsonl"))
    if not metric_files:
        raise SystemExit(f"No ACC metrics JSONL found under {model_dir}")

    by_phase_port = defaultdict(list)
    for path in metric_files:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                record = json.loads(line)
                phase = record.get("phase") or "unknown"
                for port, detail in record.get("train_port_metrics", {}).items():
                    if "q_prediction_abs_max" in detail:
                        by_phase_port[(phase, int(port))].append(detail)

    if not by_phase_port:
        raise SystemExit(
            "Metrics contain no Q diagnostics. Use a fresh run generated by "
            "the Q-diagnostics code revision."
        )

    port_rows = []
    for (phase, port), rows in sorted(by_phase_port.items()):
        port_rows.append({
            "phase": phase,
            "port": port,
            "epochs": len(rows),
            "updates": sum(int(row.get("updates", 0)) for row in rows),
            "q_prediction_abs_max": maximum(rows, "q_prediction_abs_max"),
            "q_target_abs_max": maximum(rows, "q_target_abs_max"),
            "td_error_abs_p95_max": maximum(rows, "td_error_abs_p95_max"),
            "td_error_abs_max": maximum(rows, "td_error_abs_max"),
            "expected_q_bound": float(rows[-1]["expected_q_bound"]),
            "inflation_limit": float(rows[-1]["q_inflation_limit"]),
            "inflation_events": sum(
                int(row.get("q_inflation_events", 0)) for row in rows
            ),
            "inflated": any(bool(row.get("q_inflated")) for row in rows),
        })

    phase_rows = []
    for phase in sorted({row["phase"] for row in port_rows}):
        selected = [row for row in port_rows if row["phase"] == phase]
        phase_rows.append({
            "phase": phase,
            "ports": len(selected),
            "inflated_ports": sum(row["inflated"] for row in selected),
            "inflation_events": sum(row["inflation_events"] for row in selected),
            "q_prediction_abs_max": max(row["q_prediction_abs_max"] for row in selected),
            "q_target_abs_max": max(row["q_target_abs_max"] for row in selected),
            "td_error_abs_p95_max": max(row["td_error_abs_p95_max"] for row in selected),
            "expected_q_bound": selected[0]["expected_q_bound"],
            "inflation_limit": selected[0]["inflation_limit"],
            "inflated": any(row["inflated"] for row in selected),
        })

    result = {
        "inflated": any(row["inflated"] for row in phase_rows),
        "definition": (
            "A batch is flagged when Q prediction or Bellman-target absolute "
            "p95/max exceeds q_inflation_factor times 1/(1-gamma)."
        ),
        "phases": phase_rows,
        "ports": port_rows,
    }
    output_json = args.run_dir / "q_diagnostics.json"
    output_json.write_text(
        json.dumps(result, indent=2, sort_keys=True), encoding="utf-8"
    )

    lines = [
        "# ACC Q-value diagnostics",
        "",
        f"- Overall Q inflation detected: **{'YES' if result['inflated'] else 'NO'}**",
        "- Expected scale uses bounded reward and `1 / (1 - gamma)`.",
        "- A warning is descriptive evidence of scale instability, not a policy-quality gate.",
        "",
        "| Phase | Ports | Inflated ports | Events | Q pred abs max | Q target abs max | TD abs p95 max | Expected bound | Warning limit |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in phase_rows:
        lines.append(
            f"| {row['phase']} | {row['ports']} | {row['inflated_ports']} | "
            f"{row['inflation_events']} | {row['q_prediction_abs_max']:.4f} | "
            f"{row['q_target_abs_max']:.4f} | {row['td_error_abs_p95_max']:.4f} | "
            f"{row['expected_q_bound']:.2f} | {row['inflation_limit']:.2f} |"
        )

    inflated = sorted(
        (row for row in port_rows if row["inflated"]),
        key=lambda row: max(
            row["q_prediction_abs_max"], row["q_target_abs_max"]
        ),
        reverse=True,
    )
    lines.extend(["", "## Most inflated ports", ""])
    if inflated:
        lines.extend([
            "| Phase | Port | Events | Q pred abs max | Q target abs max | TD abs max |",
            "|---|---:|---:|---:|---:|---:|",
        ])
        for row in inflated[:20]:
            lines.append(
                f"| {row['phase']} | {row['port']} | {row['inflation_events']} | "
                f"{row['q_prediction_abs_max']:.4f} | {row['q_target_abs_max']:.4f} | "
                f"{row['td_error_abs_max']:.4f} |"
            )
    else:
        lines.append("No port crossed the configured warning limit.")

    output_md = args.run_dir / "Q_DIAGNOSTICS.md"
    output_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Q diagnostics written to {output_md}")
    print(f"Q inflation detected: {'YES' if result['inflated'] else 'NO'}")


if __name__ == "__main__":
    main()
